-- Which region has the highest positive total energy?
SELECT region, SUM(net_generation - demand) as total_energy
FROM intel.energy_data
GROUP BY region
ORDER BY total_energy DESC

-- What are the top two regions for total renewable energy production?
SELECT region, SUM(solar + hydropower_and_pumped_storage + wind) as total_renewable_energy
FROM intel.energy_data
GROUP BY region
ORDER BY total_renewable_energy DESC

-- Calculates the percentage of renewable energy by region.
SELECT region, (SUM(solar + hydropower_and_pumped_storage + wind)/SUM(net_generation))*100 as percentage_renewable_energy
FROM intel.energy_data
GROUP BY region
ORDER BY percentage_renewable_energy DESC

-- Calculate renewable energy generated by each region and date
SELECT date, region, SUM(solar + hydropower_and_pumped_storage + wind) AS energy_generated_mw
FROM intel.energy_data
Group by date, region

-- Include the energy_type column
SELECT date, region, SUM(solar + hydropower_and_pumped_storage + wind) AS energy_generated_mw, 'renewable energy' as energy_type
FROM intel.energy_data
Group by date, region

-- Calculates the fossil fuel energy generated by regions
SELECT date, region, SUM(all_petroleum_products + coal + natural_gas + nuclear + other_fuel_sources) AS energy_generated_mw
FROM intel.energy_data
Group by date, region

-- Include the energy_type column
SELECT date, region, SUM(solar + hydropower_and_pumped_storage + wind + other_fuel_sources) AS energy_generated_mw, 'fossil fuel energy' as energy_type
FROM intel.energy_data
Group by date, region

-- Union fossil fuel energe and renewable energy
SELECT date, region, SUM(solar + hydropower_and_pumped_storage + wind + other_fuel_sources) AS energy_generated_mw, 'renewable energy' as energy_type
FROM intel.energy_data
Group by date, region
UNION ALL
SELECT date, region, SUM(solar + hydropower_and_pumped_storage + wind + other_fuel_sources) AS energy_generated_mw, 'fossil fuel energy' as energy_type
FROM intel.energy_data
Group by date, region

-- Join the intel.power_plants and intel.energy_by_power_plant data on the plant_code
SELECT *
FROM intel.energy_by_plant as a
INNER JOIN intel.power_plants as b
ON a.plant_code = b.plant_code

--  Which region has the most renewable power plants?
WITH energy_table as 
(SELECT *
FROM intel.energy_by_plant as a
INNER JOIN intel.power_plants as b

ON a.plant_code = b.plant_code)

SELECT region, COUNT(*) as n_plant
from energy_table
where energy_type = 'renewable_energy'
GROUP BY region
Order by n_plant DESC

-- The total number of power plants and the total energy generated, specifically from plants that use “Solar Photovoltaic” technology, grouped by each region
WITH energy_table as 
(SELECT *
FROM intel.energy_by_plant as a
INNER JOIN intel.power_plants as b

ON a.plant_code = b.plant_code)

SELECT region, COUNT(*) as n_plant, sum(energy_generated_mw) as total_energy_generated
from energy_table
where energy_type = 'renewable_energy' and primary_technology = 'Solar Photovoltaic'
GROUP BY region
Order by n_plant DESC

-- Regions having at least 50 power plants that use “Solar Photovoltaic” technology
WITH energy_table as 
(SELECT *
FROM intel.energy_by_plant as a
INNER JOIN intel.power_plants as b

ON a.plant_code = b.plant_code)
SELECT region, COUNT(*) as n_plant, sum(energy_generated_mw) as total_energy_generated
from energy_table
where primary_technology = 'Solar Photovoltaic'
GROUP BY region
HAVING COUNT(*) >= 50
Order by n_plant DESC

-- Calculates the total renewable energy generated in each region for each hour of the day
SELECT 
    region,
    DATE_PART('hour', time_at_end_of_hour) AS hour_of_day,
    SUM(solar + hydropower_and_pumped_storage + wind) AS total_renewable_energy
FROM 
    intel.energy_data
GROUP BY 
    region, hour_of_day
ORDER BY 
    region, hour_of_day;

-- Filter to the ‘California’ and ‘Northwest’ regions
SELECT 
    region,
    DATE_PART('hour', time_at_end_of_hour) AS hour_of_day,
    SUM(solar + hydropower_and_pumped_storage + wind) AS total_renewable_energy
FROM 
    intel.energy_data
WHERE region = 'California' or region = 'Northwest'
GROUP BY 
    region, hour_of_day
ORDER BY 
    region, hour_of_day;













